TerramarResqueBundle_homepage:
  path:      /
  defaults:  { _controller: TerramarResqueBundle:Default:index }

TerramarResqueBundle_queue_show:
  path:      /queue/{queue}
  defaults:  { _controller: TerramarResqueBundle:Default:showQueue }

TerramarResqueBundle_failed_list:
  path:      /failed
  defaults:  { _controller: TerramarResqueBundle:Default:listFailed }

TerramarResqueBundle_clear_failed:
  path:      /failed/clear
  defaults:  { _controller: TerramarResqueBundle:Default:clearFailed }

TerramarResqueBundle_scheduled_list:
  path:      /scheduled
  defaults:  { _controller: TerramarResqueBundle:Default:listScheduled }
