parameters:
  terramar.resque.class:
  terramar.resque.prefix:
  terramar.resque.redis.host:
  terramar.resque.redis.port:
  terramar.resque.redis.database:

services:
  terramar.resque:
    class: %terramar.resque.class%
    arguments: [ { "kernel.root_dir": %kernel.root_dir%, "kernel.debug": %kernel.debug%, "kernel.environment": %kernel.environment% } ]
    calls:
      - [ setRedisConfiguration, [ %terramar.resque.redis.host%, %terramar.resque.redis.port%, %terramar.resque.redis.database% ] ]
      - [ pruneDeadWorkers ]
